rordenlab/dcm2niix

- README.md
The first line states that the tools converts from NIfTI to DICOM formats, while I think it is the opposite.
> Fix typo: "NIfTI" <-> "DICOM"

- console/nii_dicom_batch.cpp
.bval/.bvec files use spaces instead of tabs in BIDS, when the user asks for the sidecar JSON file we should switch the delimiter assuming that .bval/.bvec files should also be BIDS compatible.
This patch does not influence the format of .bvec/.bval files if the -b flag is not used so it should not break any backwards compatibility.
> change tabs to spaces when exporting BIDS

- console/CMakeLists.txt
This PR enables **optional** integration with the system zlib and libturbojpeg libraries, which is a desirable feature for Linux distributions such as Debian or Fedora.
It introduces 2 new options, `USE_SYSTEM_ZLIB` and `USE_SYSTEM_TURBOJPEG` to selectively enable compilation with either of the system libraries. They are set to `OFF` by default in order to keep the old behaviour.
No system libraries:
```
cmake .. && make
ldd ../bin/dcm2niix
```
```
linux-vdso.so.1 (0x00007ffe2477a000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbd193c2000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbd19024000)
/lib64/ld-linux-x86-64.so.2 (0x000055f9a9efd000)
```
Use the system zlib:
```
cmake .. -DUSE_SYSTEM_ZLIB=ON && make
ldd ../bin/dcm2niix
```
```
linux-vdso.so.1 …
```
> integration with the system zlib and libturbojpeg

- console/nii_dicom_batch.cpp
The AcquisitionDateTime on the BIDS JSON sidecar wasn't formatted properly as a string.
That would case some JSON parsers to choke:
> "AcquisitionDateTime": 2016-04-12T17:29:9.218750,
```
$ jq .AcquisitionDateTime $example
parse error: Invalid numeric literal at line 5, column 38
```
> "AcquisitionDateTime": "2016-04-12T17:29:9.218750",
```
$ jq .AcquisitionDateTime $example
"2016-04-12T17:29:9.218750"
```
> Feature bids date - bugfix

- docs/source/conf.py
- docs/source/dcm2niibatch.rst
I've added a man page for dcm2niibatch as well which is based on the man page of dcm2niix. 
This addresses issue #64. Thanks @ghisvail for setting up the Sphinx documentation. It's very nice to be able to run man dcm2niibatch on the installed files.
> adding a man page for dcm2niibatch

- CMakeLists.txt
- console/CMakeLists.txt
Change cmake minimum requirements to 2.8 so that Ubuntu 14.04 is still supported. Previously one file set the minimum at 2.6 while another set it at 3.0.
> specify older cmake version in minimum requirements

- console/nii_dicom_batch.cpp
This code makes it so if tilt AND equal slicing are done, then the output name is _Tilt_Eq rather than just _Eq (which is currently done).
> trying to fix printing of tilt_eq if tilt and equal slices are done

- console/jpg_0XC3.cpp
- console/nifti1_io_core.cpp
- console/nifti1_io_core.h
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- console/nii_ortho.cpp
- console/nii_ortho.h
- console/print.h
This PR contains changes to `dcm2niix` code made in support of `divest`, as of version 0.2.0. Most are R-specific and hence fenced with `#ifdef HAVE_R`, but there are a few other tweaks:
- Arranging for `nii_saveCrop` to return a status code, similar to other, related functions.
- Adding braces to avoid compilation problems when the `divest` versions of the various print macros are used.
- Avoiding use of the `long long` type, which [can create portability problems](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#FOOT69).
> Changes from divest 0.2

- console/nii_dicom_batch.cpp
Hi Chris,
I add the `SequenceName` entry in the BIDS file to be able to keep this info when I later rename the images according to the BIDS naming scheme.
Here is my two cents I you wish to include it in your code.
Best,
Mikaël
> Add SequenceName BIDS entry

- console/CMakeLists.txt
Otherwise the build fails when both USE_SYSTEM_TURBOJPEG and BATCH_VERSION are enabled.
> Add missing linkage with TurboJPEG

- console/nii_dicom_batch.cpp
I don't know the Windows platform well, but my AppVeyor builds for `divest` are failing using the latest release of `dcm2niix`, due to missingness of `memmem`. Since the presence of this function is presumably a question of system headers rather than compiler environment, it seems like fencing the inline `memmem` implementation for Windows, rather than Visual Studio specifically, might be a more general solution. Indeed, `divest` seems to build properly on Windows like this.
> Fencing memmem implementation based on OS, not compiler

- .gitmodules
- .travis.yml
would require learning a bit about git modules but IMHO it is the correct way to do it and bind version (commit) of dcm_qa into specific state of dcm2niix.  If anything changes within dcm_qa, you would need first o push dcm_qa to github and then commit the change here
> ENH: add dcm_qa as a submodule and use in travis

- README.md
- VERSIONS.md
- console/main_console.cpp
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
This PR proposes a small feature addition to the `dcm2niix` command line interface, which allows the user to specify one or more DICOM data series that they wish to convert. 
My interest is in GUI development and data visualisation, so I would like to use `dcm2niix` in the following way:
1. Identify the DICOM series that are present, by only outputting BIDS sidecar `.json` files:
`dcm2niix -b o ...`
2. Prompt the user to select which data series they wish to view.
3. Convert those series from DICOM to NIFTI, using the proposed `-n` command line flag. For example, if the user only wishes to convert series 2 and 4, they would type:
`dcm2niix -n 2 -n 4 ...`
I am proposing this feature purely from a performance point of view - by limiting which series get converted, computational time, …
> Ability to specify which series to convert

- console/nii_dicom.cpp
Some dicom header field may contain newline (\r, \n, or \r\n) characters, which results in a syntax error of json output file. Thie pull request replaces newlines with '_', in the dcmStr function.
> mod: change new line characters to _ in the dcmStr function

- console/CMakeLists.txt
- console/nii_dicom_batch.cpp
- console/ujpeg.cpp
The `register` keyword was [deprecated in C++11 and removed in C++17](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4340), and CRAN now requires C++ code included in R packages not to use it, to avoid problems on their build farm (notably with the upcoming `clang` 6.0). This small PR removes the keyword where it is used in C++ code within `dcm2niix`, and also drops the`clang` flag telling the compiler not to complain about the deprecation (which should no longer be necessary).
> Avoid using defunct "register" keyword in C++

- Philips/README.md
- README.md
- console/main_console.cpp
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- [Improved Philips PAR/REC support](https://github.com/rordenlab/dcm2niix/issues/171)
- [Improved Philips Enhanced DICOM support](https://github.com/rordenlab/dcm2niix/issues/170)
- [Improved GE support](https://github.com/rordenlab/dcm2niix/issues/163)
- Uses proprietary GE Protocol Data Block (0025,101B).
- Assumes raw text - reports exist of a [xml variant](https://groups.google.com/forum/#!msg/comp.protocols.dicom/mxnCkv8A-i4/W_uc6SxLwHQJ) 
- Slice timing mimics dicm2nii. Assumes continuous acquisition (e.g. we do not know how to detect GE sparse acquisitions) and single-band (we do not know how to detect GE multi-band).
> Improved support of Philips and GE features

- .gitignore
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
This patch makes dcm2niix more robust to manipulation of Philips DICOM enhanced images.
Critical diffusion parameters are stored Philips private SQs such as 0018,9117. Conversion to implicit VR using dcmconv +ti ex.DCM im.DCM removes the "SQ" VRs, and the resulting tag explicitly provides the length for the whole SQ. The private SQs effectively become old-DICOM style shadow groups. This requires an explicit dictionary that identifies which private tags are actually SQs.
> Philips enhanced survive implicit

- console/nifti1_io_core.cpp
- console/nifti1_io_core.h
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- console/nii_ortho.cpp
- console/nii_ortho.h
- console/print.h
- console/ujpeg.cpp
Some unobtrusive changes from across recent versions of `divest`, so as to keep the two code-bases in line: a change in the fencing marker for R (`HAVE_R` -> `USING_R`, since the latter is defined by R itself), and some adjustments to work around compiler and `valgrind` warnings – the latter due to a fairly heavy stack allocation, which I avoid.
I think the continuous integration is currently failing on the `master` branch of `dcm2niix`, so it will fail here too, but I don't see any additional failures [on Travis](https://travis-ci.org/jonclayden/divest/jobs/429532537).
> Changes from divest, up to version 0.6.1

- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
* Fixes https://github.com/rordenlab/dcm2niix/issues/262
> Respect pixel padding value during interpolation

- console/nii_dicom.cpp
- console/nii_dicom.h
- Bruker 4D datasets: Fix parametric maps grouping
Fix incorrect combining of parametric maps into one Nifti file (#282)
- Bruker 4D datasets: correct slice ordering
Use Dimension Index Sequence (0020,9222) to identify elements of
Dimension Index Values (0020,9157) and re-order them such that In-Stack
Position Number (0020,9057) is always first, and hence slices are
correctly grouped together.
Resolves #282
> Bruker 4D dataset slice ordering / file grouping

- console/nii_dicom_batch.cpp
Sorry to miss your release with this, but I’ve now tested the updated slice timing code and made the necessary modifications to get it working correctly with `divest`. I’ve also added an extra `myReadAsciiCsa` fence to get the code to compile without that flag set – I assume this would be needed for `dcm2niix` builds too.
> Slice timing (divest)

- console/nifti1_io_core.cpp
- console/nifti1_io_core.h
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
- console/tinydir.h
This covers the changes to the core code made for `divest`, up to version 0.9.0, rebased onto the `development` branch. They mostly fix some compile-time issues, including warnings from certain compilers, and get the R codepaths to match the main ones when handling diffusion acquisitions with b=0 throughout.
> Changes from divest 0.9

- console/nii_dicom_batch.cpp
The code introduced in commit d88da85 to (once again) collapse underscores in filenames seems to appear too late in the logic of the function, if subdirectories need to be created. In this case the uncollapsed directory name will be created, resulting in a subsequent failure to create files within the directory with the collapsed name, since it hasn't been created.
I've moved this logic slightly earlier in the function to resolve the issue. This seems to work correctly in my limited testing, but I may have missed some possible code-paths so it's worth double-checking the new placement.
> Remove redundant underscores before creating subdirectories

- SuperBuild/SuperBuild.cmake
* Change displayed OpenJPEG directory from hard coded 2.1 to actual
Currently, when -DUSE_OPENJPEG=true is set in cmake, the OpenJPEG_DIR
variable is hard coded to ${OPENJPEG_LIBDIR}/openjpeg-2.1, no matter
the actual OpenJPEG version that is installed. This causes the message
`message("--   Using OpenJPEG library from ${OpenJPEG_DIR}")`
to always display `Using OpenJPEG library from /usr/lib64/openjpeg-2.1`
This message is incorrect because version 2.1 of OpenJPEG may not be
in use, and also the directory `/usr/lib64/openjpeg-2.1` may not exist
at all. In addition, this can be confusing because the message above it
can display `Found libopenjp2, version 2.4.0`, which is the correct
version of OpenJPEG.
As stated in the COMPILE.md, "Some JPEG2000 DICOM images can not be
decoded by the …
> Display correct OpenJPEG library directory

- README.md
MacPorts has dcm2niix available; a +docs variant is available for those desiring a man page, and it is installed with openjpeg and batch support. Pre-compiled binaries are available for ease of installation with the default MacPorts configuration.
> Include MacPorts option for installation.

- console/nii_dicom_batch.cpp
After our validation testings, we feel confident to remove this earning message for early GE HyperBand dataset.
> Remove warning for early GE HyperBand dataset after validation

- BATCH.md
- batch_config.yml
- console/main_console_batch.cpp
- docs/source/dcm2niibatch.rst
With this change, people who copy/paste the example batch configuration YAML will get the default behaviour. This could have saved me a lot of debugging :-)
> Fix the example batch config to match defaults

- console/nii_dicom.cpp
GE bias value for b-value
Fix for https://github.com/rordenlab/dcm2niix/issues/602
> GE bias value for b-value

- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
Please review the changes, especially for the "only set for GE fieldmaphz", please let me know if you have any suggestions.
> GE Direct field mapping (TE1/TE2) (#617)

- console/nii_dicom.cpp
I have extensively tested datasets with different combinations of Freq. and phase encoding directions/polarity including DV26, Rx29.1, MR30 software versions. This commit fixed the #674 issue.
> GE phase encoding polarity with (0018, 9034)

- GE/README.md
- console/nii_dicom_batch.cpp
This is a fix for correcting TotalReadoutTime and EffectiveEchoSpacing in the BIDS (.json) sidecar in case of image interpolation.
TotalReadoutTime and EffectiveEchoSpacing were correct when there was no interpolation (i.e. AcquisitionMatrixPE = ReconMatrixPE). However, when interpolation was used, this values were incorrect. When interpolation was used, the estimated fieldmap given by TOPUP was ReconMatrixPE/AcquisitionMatrixPE times a measured fieldmap. Also, the same interpolated images corrected with a B0Map based method via FSL's epi_reg were clearly under-corrected.
It turned out that the problem was coming from TotalReadoutTime and EffectiveEchoSpacing which were not taking ReconMatrixPE correctly into account.
This is a Fix for that.
GE/README.md was modified to clarified how …
> Dev fix TotalReadoutTime for GE with interpolation

- GE/README.md
It is now clarified that the `EchoSpacing` variable is the GE private DICOM field "(0043,102C) Effective Echo Spacing".
On branch fix-documentation-GE-TotalReadoutTime
Changes to be committed:
modified:   GE/README.md
> Documentation fix for GE TotalReadoutTime.

- GE/README.md
- console/nii_dicom_batch.cpp
Fix typos in GE/README.md and code mofification to add the intermediate variables for TotalReadoutTime on GE system in debug mode only (via compilation flag MY_DEBUG).
Added a note for that in GE/README.md:
For debugging purposes, the intermediate variables `NotPhysicalTotalReadOutTimeGE`, `NotPhysicalNumberOfAcquiredPELinesGE` and `EchoSpacing` (renamed `EchoSpacingMicroSecondsGE`) are written to the BIDS-sidecar JSON file when dcm2niix is compiled with the flag `MY_DEBUG`.
On branch dev-fix-GETotalReadoutTime-doc-and-code
Changes to be committed:
modified:   GE/README.md
modified:   console/nii_dicom_batch.cpp
> Fix code and doc for GE TotalReadoutTime

- console/dcm2niix_fswrapper.cpp
- console/dcm2niix_fswrapper.h
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- console/nii_foreign.h
1. save dicom file list in MRIFSSTRUCT, return vector of MRIFSSTRUCT for multi-echo scans if isForceStackSameSeries = 0 (-m n)
2. change output file format to "%4s.%d" from "%4s.%p" to be consistent with Freesurfer dcmunpack
3. remove space, [, ] from scan description
4. implement isDumpNotConvert option to retrieve dicom info only
5. dcm2niix_fswrapper::dicomDump() - output information of series to be converted, and seriesNum-dicomflst.txt in the same directory as series-info.dat; dcm2niix_fswrapper::seriesInfoDump() - print information for given dicom series
6. don't use std::max() from <algorithm> (fix Freesurfer ubuntu18 compiler error)
> dcm2niix_fswrapper and libdcm2niixfs.a

- console/nii_dicom.h
- console/nii_dicom_batch.cpp
The PR address #779 removing `PhaseEncodingDirectionDisplayed` for GE
> Fix PhaseEncodingDirectionDisplayed for GE #779

- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
Three updates in line with the `divest` fork: one relating to `divest`'s own interface, one relating to `dcm2niix`'s use of the JasPer API, and one on logical operators.
> Changes from divest v1.0

- console/dcm2niix_fswrapper.cpp
- console/dcm2niix_fswrapper.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- dcm2niix_fswrapper: allow subset of dcm2niix options to be set through mri_convert
- dcmListDump(): use environment variable MGH_DCMUNPACK_IMAGELIST to communicate with dcm2niix where to output imagelist.dat
- retrieve/output 'pulseSequenceDetails (tSequenceFileName)' from DICOM CSA header (0029,1020)
> DCM2NIIXFSLIB changes

- console/nii_dicom.cpp
Update code to include the UserData15 = 1.0 as well as 0.5 after checking GE PSD epi2.e code 
from
```
If (UHP or 7T) && (0.5 < UserData15 <1)
diffCyclingModeGE = 0 (off)
```
To 
```
If (UHP or 7T) && (0.5 <= UserData15 <= 1.0)
diffCyclingModeGE = 0 (off)
```
> GE UHP/7T Diffusion SliceTiming Update (#796)

- .github/ISSUE_TEMPLATE/bug_report.md
- dcm2niix/__init__.py
Updated pull request to `development` as per request at: https://github.com/rordenlab/dcm2niix/pull/823
> Console script return status code

- console/nii_dicom_batch.cpp
That change is necessary for heudiconv logic in `heudiconv.convert.update_complex_name` triggering `RuntimeError("Data type could not be inferred from the metadata.")`.
https://github.com/nipy/heudiconv/blob/68231ef2dc9bfc603c2f925c3ec00c98dd6681b4/heudiconv/convert.py#L334-L340
Otherwise, it would require heudiconv to assume `MAGNITUDE`  by default, while we reliably have that information from the dicoms at the conversion stage.
> add MAGNITUDE to ImageType for GE data 

- console/nii_dicom_batch.cpp
On Windows, when NRRD file was written into .nrrd format with raw pixels then the image was corrupted.
The root cause was that the file was opened in text mode and therefore each 0a byte was converted to 0d0a resulting in an incorrect byte stream.
> Fix corrupted raw nrrd file output on Windows

- console/nii_dicom_batch.cpp
Reverts rordenlab/dcm2niix#841 all changes must be to development branch
> Revert "Fix corrupted raw nrrd file output on Windows"

- BIDS/README.md
- console/nii_dicom.cpp
- console/nii_dicom.h
BIDS TablePosition = the 3rd value of (0043,10b2) – the value of (0019,107f)
> GE TablePosition tableDelta

- .github/ISSUE_TEMPLATE/bug_report.md
- console/dcm2niix_fswrapper.cpp
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
This parallels my PR to bids-specification:
https://github.com/bids-standard/bids-specification/pull/1772
https://github.com/bids-standard/bids-specification/issues/1709
The goal is to add DeidentificationMethod and DeidentificationMethodCodeSequence to json, so that users downstream have a chance to be informed of whether some tags were scrubbed and/or if any de-facing or other image scrubbing was applied.
From our email discussion, I understand that you will probably not merge this until bids-specification merges theirs. I thought we could iterate on this, if needed, in the meantime.
Thanks for your consideration,
Chris Schwarz
Mayo Clinic
> Add DeidentificationMethod and DeidentificationMethodCodeSequence to json

- .codespellrc
- console/nii_dicom.cpp
Also adapt allow-list to the latest codespell dictionaries.
> Fix typo found by codespell

- console/nii_dicom_batch.cpp
* Was a single string separated by \\: "xx\\yy"
* Now a json list ["xx", "yy"]
* Also now includes DeidentificationMethod when encountered without DeidentificationMethodCodeSequence
> Reformat json DeidentificationMethod

- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
Changes to the core codebase incorporated into `divest` 1.1, both for R compatibility and to address various runtime issues identified by `clang` ASan/UBSan and `valgrind`. One of the latter fixes is fenced using `USING_R`, as I'm not totally confident that it's the right change in the right place.
> Changes from divest 1.1

- console/nii_dicom.h
Attempt to live within [PyPi](https://github.com/pypi/support/issues/5269#issuecomment-2543234406) limits by disabling `submodules: recursive` from release.yml
> PyPi release
