- CMakeLists.txt
- cmake/Modules/FindNIFTI.cmake
- console/CMakeLists.txt
- console/config.h.in
- console/nifti1_io_core.cpp
- console/nifti1_io_core.h
- console/nifti1_io_ext.cpp
- console/nifti1_io_ext.h
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
- console/nii_io.mm
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>
> allow nifti, openjpeg2 be system

- README.md
- console/CMakeLists.txt
adding an option to include a downloaded version of yaml-cpp + small improvments to cmake
> cmake improvements

- console/CMakeLists.txt
> Fix for potential Sierra issue

- console/nii_dicom_batch.cpp
> Add AcquisitionDateTime to BIDS sidecard

- console/nii_dicom.cpp
I've recently created [`divest`](https://github.com/jonclayden/divest), a fork of `dcm2niix` packaged for R, and since published R packages are [automatically tested](https://cran.r-project.org/web/checks/check_results_divest.html) on several platforms the code gets exercised quite well. One thing that came up is that on SPARC/Solaris, a big-endian platform, `divest` was producing segfaults. I traced this to the code for reading CSA blocks, which are always stored little endian, but whose elements weren't previously byte-swapped.
In this PR I'm including some edits to byte-swap elements of the CSA-related `struct`s that are subsequently used by the code. I also check system endianness more robustly, rather than relying on the `__BIG_ENDIAN__` constant, which [isn't always …
> Improving support for big-endian systems

- README.md
update README to reflect ability to install on system (with manpages).
> update README to include install option.

- Dockerfile
for those who want the portability...
> Docker version of dcm2niix

- README.md
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
[better handling of classic Philips data](https://github.com/rordenlab/dcm2niix/issues/170)
> Use ImageType (0008,0008) to split phase and magnitude

- README.md
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- By default, `myReadGeProtocolBlock` is not defined
- Fix regression for reading encapsulated data (@yarikoptic)
> Disable reading GE Protocol Block 

- README.md
- VERSIONS.md
- console/main_console.cpp
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
Better support for [unusual](https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Unusual_MRI) Philips enhanced images with multiple echo, cardiac, dynamic, type [magnitude, phase, real, imaginary] data.
> Philips enhanced survive implicit

- console/nii_dicom_batch.cpp
See (https://github.com/rordenlab/dcm2niix/issues/163)
> flip polarity of PE direction for GE to match Siemens

- console/nii_dicom_batch.cpp
> Reflect negative tilt padding in image origin

- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
Changes for full R compatibility with the latest `dcm2niix` release. Individual commits retained for transparency, but do feel free to squash them to avoid cluttering your history.
> Changes from divest 0.10

- console/nii_dicom_batch.cpp
I made two changes:
1) sliceTiming = -1 for version < 26
2) Warning message for early GE HB when slice/HB is even
> Warning message for early GE HyperBand

- SuperBuild/SuperBuild.cmake
- console/CMakeLists.txt
- console/dcm2niix_fswrapper.cpp
- console/dcm2niix_fswrapper.h
- console/nifti1_io_core.cpp
- console/nifti1_io_core.h
- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
> Add option to build libdcm2niixfs.

- console/nii_dicom.cpp
- console/nii_dicom_batch.cpp
Very minor changes against the current development branch for `divest` 0.10.2.
I want to make bigger changes to avoiding duplicating logic from the BIDS writer, but that's a bigger job and I'm still trying to work out how best to do it, so it can wait for now.
> Changes for divest 0.10.2

- console/main_console.cpp
- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
- Improved GE software version reading (version 30) #634 
- Added SliceTiming for GE Diffusion #635 
- New keys added in JSON for GE diffusion:
> NumberOfDiffusionDirectionGE
> NumberOfDiffusionT2GE
> TensorFileNumberGE
> DiffGradientCyclingGE
> GE Diffusion SliceTiming

- console/nii_dicom.cpp
- console/nii_dicom.h
- console/nii_dicom_batch.cpp
- The following keys reported in JSON are limited to GE Diffusion only (#635) :
- NumberOfDiffusionDirectionGE
- NumberOfDiffusionT2GE
- TensorFileNumberGE
- DiffGradientCyclingGE
- The definition of userData12 (CV12) fro DiffGradientCyclingGE has been updated:
- userData12 (CV12) = 1 : All-TR
- userData12 (CV12) = 2: 2-TR
- userData12 (CV12) = 3: 3-TR
> GE Diffusion JSON update

- console/dcm2niix_fswrapper.cpp
- console/dcm2niix_fswrapper.h
- console/nii_dicom_batch.cpp
- console/nii_dicom_batch.h
1. set isForceStackSameSeries = 1 by default
2. make adjustments for MGH bvecs output
> dcm2niix_fswrapper and libdcm2niixfs.a

- console/nii_dicom.cpp
- console/nii_dicom.h
To support SliceTiming on GE UHP & 7T diffusion with cycling OFF
> GE UHP/7T Diffusion SliceTiming (#796)

- .github/workflows/release.yml
- .gitignore
- fixes #829
- follow-up to #605
> CI: PyPI release

- GE/README.md
Re-submitting the PR (#847) to dev branch, on behalf of @brice82 and @mharms
> Total Read-Out Time Documentation update for GEHC
